apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::816817860311:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-iBKCKYiCuhJd
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::816817860311:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-20T22:43:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1179"
  uid: e74fe8a4-647d-4b44-8765-e2804a911cfe
